### ISSUE TITLE
Editing mccExtractions.R for plotting the dispersal history

### ISSUE THREAD

**Issue by guillemmasfiol** [sdellicour/seraphim#2]
Hello,
thanks a lot in advance for creating this magnific package. After checking the provided tutorials for the different analysis using Seraphim, I attempted to perform analyses on my own dataset, which I obtained after a phylogeographic reconstruction in continuous space using BEASTv1.10 with a Cauchy RRW model. 
I would like to plot the dispersal history from the MCCtree and bayesian trees files, but unfortunately my skills on R scripting are limited. If I am not mistaken, I used the same name for the location data as in the YFV provided as tutorial example, but however when trying to run the mccExtractions.R function, the following error message appeared:

Error in mcc_tab[i, c("endLon", "endLat")] <- cbind(annotations$location2,  : 
  number of items to replace is not a multiple of replacement length

I am not sure of how should I edit the mccExtractions.R function to associate the location data on the matrix mcc_tab. You can find attached here the MCCtree for my dataset. 
I hope you may easily spot the necessary edition that I shall do on the script for being able to associate the coordinates data to the matrix.

Thanks a lot for your advice,

Guillem

[mcctree_run1.zip](https://github.com/sdellicour/seraphim/files/5119586/mcctree_run1.zip)

mccExtractions = function(mcc_tre, mostRecentSamplingDatum)
	{
		mcc_tab = matrix(nrow=dim(mcc_tre$edge)[1], ncol=7)
		colnames(mcc_tab) = c("node1","node2","length","startLon","startLat","endLon","endLat") #,"startNodeL","endNodeL","startYear","endYear")
		mcc_tab[,c("node1","node2")] = mcc_tre$edge
		mcc_tab[,c("length")] = mcc_tre$edge.length
		for (i in 1:length(mcc_tre$annotations))
			{
				annotations = mcc_tre$annotations[[i]]
				mcc_tab[i,c("endLon","endLat")] = cbind(annotations$location2, annotations$location1) # to be edited
				# mcc_tab[i,"endNodeL"] = annotations$height
			}
		for (i in 1:length(mcc_tre$annotations))
			{
				index = which(mcc_tab[,"node2"] == mcc_tab[i,"node1"])
				if (length(index) > 0)
					{
						mcc_tab[i,c("startLon","startLat")] = mcc_tab[index,c("endLon","endLat")]
						# mcc_tab[i,"startNodeL"] = mcc_tab[index,"endNodeL"]
					}	else		{
						annotations = mcc_tre$root.annotation
						mcc_tab[i,c("startLon","startLat")] = cbind(annotations$location2, annotations$location1) # to be edited
						# mcc_tab[i,"startNodeL"] = annotations$height
					}
				# mcc_tab[i,"startYear"] = mostRecentSamplingDatum - mcc_tab[i,"startNodeL"]
				# mcc_tab[i,"endYear"] = mostRecentSamplingDatum - mcc_tab[i,"endNodeL"]
			}

**Comment by guillemmasfiol** [comment]
Hello,

I'm sorry, I discovered the source of the error was inside my MCCTree file, while the mccExtractions.R function didn't need any modification in my case.

Guillem

**Comment by sanderdebacker** [comment]
Hello Guillem,

I'm getting the same error.
What was the problem with your MCCTree file? Maybe it's also the source or the error in my case.

Thanks!
