### ISSUE TITLE
can not install seraphim?

### ISSUE THREAD

**Issue by BEAST-Community** [sdellicour/seraphim#3]
> install_github("sdellicour/seraphim/unix_OS")
Downloading GitHub repo sdellicour/seraphim@HEAD
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  download from 'https://api.github.com/repos/sdellicour/seraphim/tarball/HEAD' failed

**Comment by jaberbel** [comment]
Were you able to fix it @BEAST-Community? I'm facing the same issue. Thx

**Comment by zbouslama** [comment]
@BEAST-Community 
I have the same error , too. were you able to fix it ?

**Comment by jsan4christ** [comment]
Have the same issue...on macos;
> install_github("sdellicour/seraphim/unix_OS")
Downloading GitHub repo sdellicour/seraphim@HEAD
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  download from 'https://api.github.com/repos/sdellicour/seraphim/tarball/HEAD' failed



> session_info()
─ Session info ─────────────────────────────────────────────────────────────────────────────────────────────────
 setting  value                       
 version  R version 4.0.5 (2021-03-31)
 os       macOS Big Sur 10.16         
 system   x86_64, darwin17.0          
 ui       RStudio                     
 language (EN)                        
 collate  en_US.UTF-8                 
 ctype    en_US.UTF-8                 
 tz       Africa/Johannesburg         
 date     2022-05-23

**Comment by jsan4christ** [comment]
I managed to get over this one. In my case the issue was the size of the package. Seraphim is more than 200M which can take a while to install. By default, R will timeout after 60 seconds of the install process. To allow more time for the installation process to succeed, use; 

options(timeout=9999999)

Alternatively, switch to a very high speed connection such as a corporate network that is orders of magnitude faster than your home or mobile connection.

I hope that helps someone else in a similar situation.

**Comment by sdellicour** [comment]
One way to fix the current installation issue on MacOS (when installing directly from GitHub) is to use the following command:
> install_github("sdellicour/seraphim/unix_OS”, download.file.method = “wininet”)

**Comment by liamxg** [comment]
> install_github("sdellicour/seraphim/unix_OS", download.file.method = "wininet")
Downloading GitHub repo sdellicour/seraphim@HEAD
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  download from 'https://api.github.com/repos/sdellicour/seraphim/tarball/HEAD' failed
Error in `action()`:
! `class` is absent but must be supplied.
Run `rlang::last_error()` to see where the error occurred.

**Comment by liamxg** [comment]
still have problem, who can help me, thanks.

**Comment by sdellicour** [comment]
@LiXingguangBrandonStark are you on MacOS or Unix? If so, could you try the installation from a Terminal window? (i) Launch R (simply enter 'R' in the Terminal), (ii) load the 'devtools' library > library(devtools), (iii) install 'seraphim' from GitHub > install_github("sdellicour/seraphim/unix_OS")

**Comment by liamxg** [comment]
Dear @sdellicour I am using MacOS.

**Comment by liamxg** [comment]
<img width="469" alt="image" src="https://user-images.githubusercontent.com/46078579/189820655-be09c483-5809-4c15-8848-ebe7ecfb4564.png">

**Comment by liamxg** [comment]
still not work

**Comment by sdellicour** [comment]
I am not aware of such an issue on MacOS. Which OS version do you have?

**Comment by sdellicour** [comment]
Not sure this will solve the issue but you could always try updating it
