### ISSUE TITLE
error

### ISSUE THREAD

**Issue by liamxg** [sdellicour/seraphim#5]
<img width="755" alt="image" src="https://github.com/sdellicour/seraphim/assets/46078579/1ecb6eaa-8b6b-46b1-85d3-ae8fcf38c70b">

**Comment by liamxg** [comment]
when I run "treeExtractions(localTreesDirectory, allTrees, burnIn, randomSampling, nberOfTreesToSample, mostRecentSamplingDatum, coordinateAttributeName)"

**Comment by liamxg** [comment]
@sdellicour

**Comment by sdellicour** [comment]
Difficult to help solely looking at the error message. Could you share your script and one input file by e-mail?

**Comment by liamxg** [comment]
@sdellicour sure, could you share your email with me, thanks.

**Comment by sdellicour** [comment]
simon.dellicour@ulb.be

**Comment by liamxg** [comment]
@sdellicour sent, thanks.
