### ISSUE TITLE
why need we install `circuitscape` ?

### ISSUE THREAD

**Issue by liamxg** [sdellicour/seraphim#6]
Dear @sdellicour,

Could  you please tell me why should we install ` circuitscape`, thanks.

**Comment by sdellicour** [comment]
Because it is called by the package - see e.g. https://bmcbioinformatics.biomedcentral.com/articles/10.1186/s12859-016-0924-x

**Comment by sdellicour** [comment]
(Or the package manual for further detail)

**Comment by liamxg** [comment]
Dear @sdellicour,

Thanks, `Circuitscape` running on Python 2?  and I failed to install `Circuitscape` :

sudo -H pip install -U --upgrade circuitscape

Password:
Collecting circuitscape
  Using cached Circuitscape-4.0.5.tar.gz (89 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/tmp/pip-install-sos9211j/circuitscape_bf4051e01d23427b9731f16a939c3ac8/setup.py", line 3, in <module>
          from circuitscape import __version__, __author__, __email__
        File "/private/tmp/pip-install-sos9211j/circuitscape_bf4051e01d23427b9731f16a939c3ac8/circuitscape/__init__.py", line 1, in <module>
          from compute import Compute, __version__, __author__, __email__
      ModuleNotFoundError: No module named 'compute'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by sdellicour** [comment]
Yes, it runs on Python 2 (but you can also use the Julia version) - note that the installation of Circuitscape is however not compulsory to use the "seraphim" functions not calling this package. I cannot really help for the installation associated with Circuitscape as I didn't develop that library and have never encountered the above error message

**Comment by liamxg** [comment]
cool! Thanks.
